spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/WikiChef
    username: postgres
    password: Yupi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: SECRET_KAWAII_12345
  expiration: 86400000
JWT_SIGNING_KEY: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"