spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/WikiChef
    username: postgres
    password: Yupi
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: true
    validate-on-migrate: true
    baseline-on-migrate: true
logging:
  level:
    org.flywaydb: DEBUG
    org.flywaydb.core: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: SECRET_HOLDING_TEST_12345
  expiration: 86400000

token:
  signing:
    key: ${JWT_SIGNING_KEY:413F4428472B4B6250655368566D5970337336763979244226452948404D6351}

